### PR TITLE
Upgrade to Infinispan 9.2

### LINKED ISSUE #19: Align lock implementation with other cluster managers
This cluster manager uses JGroups locks. But Vert.x locks are not distributed locks, they are distributed semaphores with a single permit.

The JGroups locks have been configured to not use the thread id for lock owner. This allows to release the lock from a different thread.
But it also allows to acquire the same lock twice if you're on the same JVM. Two tests from the suite have been disabled because of this (`InfinispanClusteredAsynchronousLockTest#testAcquireOnSameEventLoop` and `InfinispanClusteredAsynchronousLockTest#testAcquireOnExecuteBlocking`).

### LINKED ISSUE #46: Upgrade to Infinispan 9.2
Infinispan 9.2 provides builtin multimap, locks and counters.

### LINKED ISSUE #49: different schema versions in 2 different xml files
I noticed an inconsistency in the schema version in these 2 files, one has 9.0 and the other has 9.1 -

src/main/resources/default-infinispan.xml
```
<infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:9.0 http://www.infinispan.org/schemas/infinispan-config-9.0.xsd"
            xmlns="urn:infinispan:config:9.0">

```

src/test/resources/infinispan.xml
```
<infinispan xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:schemaLocation="urn:infinispan:config:9.1 http://www.infinispan.org/schemas/infinispan-config-9.1.xsd"
            xmlns="urn:infinispan:config:9.1">
```

### PR DESCRIPTION
**Pull request by tsegismont**
Fixes #46 , fixes #19

The cluster manager uses the new ISPN features:
- multimap caches
- clustered locks
- clustered counters (strong)

### CODE REVIEW

**Comment by tsegismont** [comment]
Do not merge yet, Infinispan `9.2.0.Final` will be out soon, currently the PR is tested with 9.2.0.CR2

**Comment by karesti** [comment]
@tsegismont can be upgraded to 9.2.0.Final

**Comment by karesti** [comment]
@tsegismont any chances to merge soon ? 🙏

**Comment by tsegismont** [comment]
@karesti merged!

**Pull request merged**
