### PR TITLE
Clustering SPI update

### PR DESCRIPTION
**Pull request by tsegismont**
Follows-up on eclipse-vertx/vert.x#3132

### CODE REVIEW

**Comment by vietj** [comment]
The CI cannot pass due to time limit. Didn't we solve this problem ?

**Comment by vietj** [comment]
The CI does not complete due to time limit exceeded, however in what runs I can see unexpected issues like:

```
Object instance io.vertx.ext.cluster.infinispan.impl.SubsCacheHelper$EntryListener@3aa4b0a5 
java.lang.NullPointerException: null
	at io.vertx.core.spi.cluster.impl.DefaultNodeSelector.registrationsUpdated(DefaultNodeSelector.java:51)
	at io.vertx.ext.cluster.infinispan.impl.SubsCacheHelper.lambda$fireRegistrationUpdateEvent$1(SubsCacheHelper.java:114)
```

**Comment by tsegismont** [comment]
@vietj yes, it is the first time the test suite can run on CI, I will investigate the issues. I believe they are the reason the build does not complete in time.

**Comment by tsegismont** [comment]
@vietj PTAL

**Pull request merged**
