### PR TITLE
Shouldn't use ${project.version} for non project dependencies

### PR DESCRIPTION
**Pull request by paulgallagher75**

### CODE REVIEW

**Comment by tsegismont** [comment]
@paulgallagher75 the project doesn't compile with this change. Can you elaborate on the issue? I would like to avoid hard-coding the project version.

**Comment by paulgallagher75** [comment]
It requires a PR to vertx-dependencies to define the version of the test-jars

**Comment by tsegismont** [comment]
Have you sent it ?

**Comment by paulgallagher75** [comment]
I have now, there are 2 PR's on vertx-dependencies

**Pull request merged**
