### PR TITLE
Vert.x Web Session Store with Infinispan Client

### LINKED ISSUE #81: Infinispan Web Session Store
Vert.x Web has an SPI for web session data storage.

Infinispan is a good fit for this use case.

### PR DESCRIPTION
**Pull request by tsegismont**
Closes #81

### CODE REVIEW

**Comment by tsegismont** [comment]
ping @pmlopes @karesti 

This PR is currently based on #93 (not merged yet). Please review only the last commit(s).

**Comment by tsegismont** [comment]
@pmlopes there are 4 tests failing on my box currently, I will look into it but would appreciate any early feedback. Thanks

**Comment by pmlopes** [comment]
Just for consistency why here and not on vertx web repo like redis?

**Review by pmlopes — COMMENTED** [review]
I've just 2 comments here:

1. Shouldn't the session store be added to the `vertx-web` repo like the others?
2. I think we miss a `@VertxGen` Infinispan SessionStore interface (like we have on the others) to allow explicit creation of the session store. This is specifically useful when several store jars are on the classpath and the user wants to control the exact one to be used.

**Comment by tsegismont** [comment]
@pmlopes 

>Shouldn't the session store be added to the vertx-web repo like the others?

I thought about it. The advantage of having the sstore in this repo is removing dependency cycles between builds.
Well it's not really a problem now given the sstore does not depend on a Vert.x Infinispan Client but it may in the future.

>I think we miss a @VertxGen Infinispan SessionStore interface (like we have on the others) to allow explicit creation of the session store. This is specifically useful when several store jars are on the classpath and the user wants to control the exact one to be used.

Right. I will create it.

One thing I notices on the Redis Session Store implementation is that it misses a no-arg constructor.
I may be wrong but that means it wouldn't work with service loading, correct?

**Comment by tsegismont** [comment]
@pmlopes I have fixed the tests

**Comment by tsegismont** [comment]
@pmlopes PTAL

One thing I notice while developing this is that we have no place on the website for session store documentation.
Perhaps we should discuss that on vertx-dev?

**Comment by tsegismont** [comment]
@pmlopes I rebased the PR on master. It is ready for the formal review.

**Review by pmlopes — APPROVED** [review]

**Pull request merged**
