### PR TITLE
entryStream() throws an exception

### LINKED ISSUE #106: entryStream() throws an exception
Converting infinispan's entryStream to kotlin's ReceiveChannel throws an exception:
```
java.lang.NullPointerException: Cannot invoke "org.infinispan.commons.util.CloseableIteratorCollection.iterator()" because "this.iterable" is null
	at io.vertx.ext.cluster.infinispan.impl.CloseableIteratorCollectionStream.lambda$doRead$2(CloseableIteratorCollectionStream.java:134)
```
This can be reproduced by adding `stream.fetch(1)` to the very last line of the loadData callback (like it does in the `ReadStream<T>.toChannel()`) in `InfinispanClusteredAsyncMapTest` (reproduces occasionally).

I'll provide a PR to fix this soon.

### PR DESCRIPTION
**Pull request by ruslansennov**
fixes #106

### CODE REVIEW

**Comment by tsegismont** [comment]
If I understand correctly, the problem happens when Infinispan returns a `null` iterable, right? Why not creating new tests for this case then?

**Comment by ruslansennov** [comment]
@tsegismont  no, the problem happens when someone call `fetch()` method when the `iterable` has not yet been set on the worker thread. I have no idea how this can be tested :(

**Comment by tsegismont** [comment]
I would say this happens if you call `fetch()` before a data `handler` has been set.

**Comment by ruslansennov** [comment]
No, this also sometimes happens if you call `fetch()` right after `handler` has been set. Because `iterable` is set asynchronously on another thread. You can try running the modified test on unmodified code.

**Review by tsegismont — APPROVED** [review]

**Comment by tsegismont** [comment]
> No, this also sometimes happens if you call fetch() right after handler has been set. Because iterable is set asynchronously on another thread. You can try running the modified test on unmodified code.

Right, thanks for the good analysis and fix

**Pull request merged**
